V0.1
moka-guys/genomics_server_download pull request #1
Opened 2021-06-24 14:03 UTC by rebeccahaines1

First full commit with working script

2021-06-25 15:07 UTC, natashapinto requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/genomics_server_download/1)* status: all files reviewed, 1 unresolved discussion (waiting on @rebeccahaines1)

___
*[script.py, line 3 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2cUvd3uPdzk3yhSKH:-Md2cUvd3uPdzk3yhSKI:b-9njogd) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/script.py#L3)):*
> ```Python
> import os, datetime, subprocess
> # import config file
> import config as config
> ```

importing config as config? any reason


<!-- Sent from Reviewable.io -->

2021-06-25 15:15 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/genomics_server_download/1)* status: all files reviewed, 25 unresolved discussions (waiting on @rebeccahaines1)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2VO_J9ZabQ-etRwoo:-Md2VO_J9ZabQ-etRwop:b-b82nhv) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/README.md#L1)):*
> ```Markdown
> # genomics_server_upload
> ```

download
___
*[README.md, line 2 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2VWD05mWy0hR3J0yi:-Md2VWD05mWy0hR3J0yj:b-i3dpzx) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/README.md#L2)):*
> ```
> Genomics S
> ```
to the ArcherDx analysis platform via Genomics server
___
*[README.md, line 4 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2VkVrCPMdAN9r52-I:-Md2VkVrCPMdAN9r52-J:b98ltxo) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/README.md#L4)):*
> ```
> Currently only contains script to download fastq files for ArcherDX FusionPlex Pan Solid Tumour NGS runs
> ```
These scripts are designed to run hourly and monitor DNANexus for new ArcherDx projects. When a project is found the fastqs are downloaded and transferred to the watched folders on the server hosting the  archerdx analysis platform.

The run is demultiplexed and uploaded to DNANexus using code in the automate_demultiplex (https://github.com/moka-guys/automate_demultiplex/).

This script monitors recent DNANexus projects, searching the project name for those containing "ADX". If these have not already been processed and the data upload is complete the dxda tool is used to download the fastqs. the dxda performs an integrity check.

rsync is then used to transfer fastqs into the watched folder. rsync also checks for data integrity.

The watched folders will set off analyses when a file named analysisid_completed.txt is present. Analyses can consist of single samples or groups of samples. The lab has chosen for all samples on a run to be grouped into one analysis, so a folder is created with the name of the analysis and fastqs transferred into this folder. Once all fastqs are successfully transferred the completed file is created.
___
*[README.md, line 4 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2dsNC0LDheanoQ8es:-Md2dsNC0LDheanoQ8et:b-rlz9lh) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/README.md#L4)):*
> ```Markdown
> Scripts for downloading files from DNA Nexus to the Genomics Server (LOVD server).
> 
> Currently only contains script to download fastq files for ArcherDX FusionPlex Pan Solid Tumour NGS runs. Runs are demultiplexed and uploaded to DNA Nexus using the automated scripts. FASTQ files must then be downloaded and transfered to the Archer server in order to be used by the Archer Analysis software.
> ```

maybe also state that dxda is a series of scripts?
___
*[README.md, line 6 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2WRPT8xIl6T3HOihQ:-Md2WRPUB-KS8WOZWCZj:b-xh0o8) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/README.md#L6)):*
> ```Markdown
> Currently only contains script to download fastq files for ArcherDX FusionPlex Pan Solid Tumour NGS runs. Runs are demultiplexed and uploaded to DNA Nexus using the automated scripts. FASTQ files must then be downloaded and transfered to the Archer server in order to be used by the Archer Analysis software.
> ### Scripts for the ArcherDX file transfer:
> * script.py
> ```

can we rename script.py?
___
*[README.md, line 12 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2jEWh-lmV3IIBVpbI:-Md2jEWh-lmV3IIBVpbJ:b9s2dk7) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/README.md#L12)):*
> ```Markdown
> ## Requirements
> * Python 2.7
> * DNA Nexus dxda 
> ```

can we state what version of dxda we're currently using?
___
*[README.md, line 15 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2jJg19PX43pvRxjlt:-Md2jJg19PX43pvRxjlu:bhf7ysn) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/README.md#L15)):*
> ```Markdown
>     * CLI tool to manage the download of large quantities of files from DNAnexus (https://github.com/dnanexus/dxda)
>     * Used to create and filter a manifest file, download files based on the manifest, then check the intergrity of the download
> * Archer server password 
> ```

dnanexus sdk
___
*[README.md, line 16 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2Xm3r4g-OROXleiaz:-Md2Xm3r4g-OROXleib-:b-7jt3vc) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/README.md#L16)):*
> ```Markdown
>     * Used to create and filter a manifest file, download files based on the manifest, then check the intergrity of the download
> * Archer server password 
> * DNA Nexus API token
> ```

rsync
___
*[script.py, line 35 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2blLi0tXLVlSu-NSn:-Md2blLi0tXLVlSu-NSo:b6xylx5) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/script.py#L35)):*
> ```Python
> 				self.logger("No new Archer projects.", "Archer list projects")
> 
> 	def check_if_already_actioned(self, project):
> ```

can we describe content if project in docstring again
___
*[script.py, line 64 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2Z5BxCB9-7DbP0CdS:-Md2Z5BxCB9-7DbP0CdT:bmpnr1x) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/script.py#L64)):*
> ```Python
> 	def check_all_files_closed(self,project):
> 		"""
> 		This function makes sure all fastq files have finished uploading to DNANexus before it tries to download them
> ```

when a function has inputs and outputs can these be stated in docstring - in this case the input isn't described (hard to know it's a tuple) (projectid,projectname)
___
*[script.py, line 79 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2b6E7EXlhFYS9Cr3B:-Md2b6E7EXlhFYS9Cr3C:b-rz9ns5) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/script.py#L79)):*
> ```
> rcher project %s
> ```
If this becomes an issue in future we may want to state the file that is not closed at this stage (filename is captured below)
___
*[script.py, line 82 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2bRrXAsBNv1KOEOUY:-Md2bRrXAsBNv1KOEOUZ:b8op92x) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/script.py#L82)):*
> ```Python
> 				all_files_closed = False
> 			# add filename to list and to logfile
> 			if len(line) > 2:
> ```

this seems to be happening even if the file is closed?
___
*[script.py, line 100 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2cx1d5cQsALD7NL0g:-Md2cx1d5cQsALD7NL0h:bj0uz5v) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/script.py#L100)):*
> ```Python
> 		login will time out after 30 mins
> 		"""
> 		cmd = config.source_command+";dx login --token %s --noprojects --timeout 30m" % (config.Nexus_API_Key)
> ```

--no-projects doesn't require a project to be selected which would otherwise require an additional response.
___
*[script.py, line 109 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1 [...]

2021-06-25 15:27 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/genomics_server_download/1)* status: all files reviewed, 30 unresolved discussions (waiting on @rebeccahaines1)

___
*[script.py, line 75 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2ksmA2purpJ6i7B3I:-Md2ksmA2purpJ6i7B3J:bq5ock0) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/script.py#L75)):*
> ```
> \n
> ```
can we put a colon at the end here?
___
*[script.py, line 85 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2l-Ih8OCYcK7HmYEc:-Md2l-Ih8OCYcK7HmYEd:b-phjnkx) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/script.py#L85)):*
> ```
> filenam
> ```
can we indent this or put a - to make it clear it's a list in logfile
___
*[script.py, line 235 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2lZpi7t4YBkAC2ith:-Md2lZpi7t4YBkAC2iti:b-jgket1) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/script.py#L235)):*
> ```Python
> 				runnumber = "ADX"+fastq.split("ADX")[1].split("_")[0]
> 				file_to_transfer = os.path.join(config.download_location, project[1].replace("003_","").replace("002_",""),config.fastq_folder_path, fastq)
> 				self.logger("file to transfer %s" % file_to_transfer, "Archer file transfer")
> ```

in the logfile there are tabs between commands. could we replace these (file_to_transfer.replace("\t",""))
Also put prefix with cmd to distinguish between the previous line and the cmd
___
*[script.py, line 235 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2lu1457ujI1xQQCU7:-Md2lu1457ujI1xQQCU8:bfettml) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/script.py#L235)):*
> ```
> Archer 
> ```
Archer not needed here
___
*[script.py, line 385 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2lAosE0N8Aiv3kbY7:-Md2lAosE0N8Aiv3kbY8:ba2gyxu) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/script.py#L385)):*
> ```Python
> 		if subprocess.call([log], shell=True) == 0:
> 			# If the log command produced no errors, record the log command string to the script logfile.
> 			self.script_logfile.write("Log written - " + tool + ": " + message + "\n")
> ```

do we need log written here?


<!-- Sent from Reviewable.io -->

2021-06-25 15:33 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/genomics_server_download/1)* status: all files reviewed, 31 unresolved discussions (waiting on @rebeccahaines1)

___
*[script.py, line 33 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2n7V2E8YsOiNboob8:-Md2n7V30Pe8_EQiQYPg:bbkbqyq) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/script.py#L33)):*
> ```Python
> 				yield (projectid, projectname)
> 			else:
> 				self.logger("No new Archer projects.", "Archer list projects")
> ```

this could be the on;y thing in logfile or with multiple others, maybe it could say No outstanding ArcherDx projects found?


<!-- Sent from Reviewable.io -->

2021-06-28 12:30 UTC, rebeccahaines1 reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/genomics_server_download/1)* status: 1 of 4 files reviewed, 31 unresolved discussions (waiting on @aledj2 and @natashapinto)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2VO_J9ZabQ-etRwoo:-MdHOJlkE4bT27quq1dK:b-896fix) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/README.md#L1)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

download
</blockquote></details>

Done.
___
*[README.md, line 2 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2VWD05mWy0hR3J0yi:-MdHOvvL3nFSYtzFak3R:bvg2drk) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/README.md#L2)):*
> to the ArcherDx analysis platform via Genomics server
I had left this general because I thought the idea was that this might be used for things other than the archer transfer. Have made the change as suggested.
___
*[README.md, line 4 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2VkVrCPMdAN9r52-I:-MdHQ-Mc9P221tfQiX0c:b-896fix) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/README.md#L4)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> Currently only contains script to download fastq files for ArcherDX FusionPlex Pan Solid Tumour NGS runs
> ```
These scripts are designed to run hourly and monitor DNANexus for new ArcherDx projects. When a project is found the fastqs are downloaded and transferred to the watched folders on the server hosting the  archerdx analysis platform.

The run is demultiplexed and uploaded to DNANexus using code in the automate_demultiplex (https://github.com/moka-guys/automate_demultiplex/).

This script monitors recent DNANexus projects, searching the project name for those containing "ADX". If these have not already been processed and the data upload is complete the dxda tool is used to download the fastqs. the dxda performs an integrity check.

rsync is then used to transfer fastqs into the watched folder. rsync also checks for data integrity.

The watched folders will set off analyses when a file named analysisid_completed.txt is present. Analyses can consist of single samples or groups of samples. The lab has chosen for all samples on a run to be grouped into one analysis, so a folder is created with the name of the analysis and fastqs transferred into this folder. Once all fastqs are successfully transferred the completed file is created.
</blockquote></details>

Done.
___
*[README.md, line 4 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2dsNC0LDheanoQ8es:-MdHQA7m551rhixg-GcS:b-896fix) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/README.md#L4)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

maybe also state that dxda is a series of scripts?
</blockquote></details>

Done.
___
*[README.md, line 6 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2WRPT8xIl6T3HOihQ:-MdGv02ZEX0cHZY6KmO2:b-er2fwo) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/README.md#L6)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can we rename script.py?
</blockquote></details>

Done. renamed script.py to archer_script.py and config.py to archer_config.py
___
*[README.md, line 12 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2jEWh-lmV3IIBVpbI:-MdH0VyoDdH8-9sey_8y:b-arclqv) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/README.md#L12)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can we state what version of dxda we're currently using?
</blockquote></details>

I think it's v0.5.5, based on comparing what we have on the server with github.
___
*[README.md, line 15 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2jJg19PX43pvRxjlt:-MdHQJBj7JJyGdDxWkYg:b-896fix) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/README.md#L15)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

dnanexus sdk
</blockquote></details>

Done.
___
*[README.md, line 16 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2Xm3r4g-OROXleiaz:-MdHQJ_88P6SDmp9Qw-s:b-896fix) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/README.md#L16)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

rsync
</blockquote></details>

Done.
___
*[script.py, line 3 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2cUvd3uPdzk3yhSKH:-MdGegqEBKrpKalqnuLA:bs00f6n) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/script.py#L3)):*
<details><summary><i>Previously, natashapinto wrote…</i></summary><blockquote>

importing config as config? any reason
</blockquote></details>

no, but now changed config file name so updated this to reflect change
___
*[script.py, line 33 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2n7V2E8YsOiNboob8:-MdGfKGv30CmgBkyyWhA:b-896fix) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/script.py#L33)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

this could be the on;y thing in logfile or with multiple others, maybe it could say No outstanding ArcherDx projects found?
</blockquote></details>

Done.
___
*[script.py, line 35 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2blLi0tXLVlSu-NSn:-MdH0mJh81R8fGL5qq8P:b-896fix) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/script.py#L35)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can we describe content if project in docstring again
</blockquote></details>

Done.
___
*[script.py, line 64 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2Z5BxCB9-7DbP0CdS:-MdGuJdC8J1ssx851BiO:b-896fix) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/script.py#L64)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

when a function has inputs and outputs can these be stated in docstring - in this case the input isn't described (hard to know it's a tuple) (projectid,projectname)
</blockquote></details>

Done.
___
*[script.py, line 75 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2ksmA2purpJ6i7B3I:-MdGlhACCm7HC23aKbrk:b-896fix) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/script.py#L75)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> \n
> ```
can we put a colon at the end here?
</blockquote></details>

Done.
___
*[script.py, line 79 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2b6E7EXlhFYS9Cr3B:-MdH1zx8DE_gySA8Kr3o:b-896fix) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/script.py#L79)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> rcher project %s
> ```
If this becomes an issue in future we may want to state the file that is not closed at  [...]

2021-06-28 14:45 UTC, aledj2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-:-MdI4DetDG9w88JAbJgP:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[README.md, line 2 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2VWD05mWy0hR3J0yi:-MdI3ZRq93b2DK7X1d7R:b3h1537) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/README.md#L2)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

> to the ArcherDx analysis platform via Genomics server
I had left this general because I thought the idea was that this might be used for things other than the archer transfer. Have made the change as suggested.
</blockquote></details>

I think we can update as/when additional use cases arise
___
*[script.py, line 235 at r1](https://reviewable.io/reviews/moka-guys/genomics_server_download/1#-Md2lu1457ujI1xQQCU7:-MdI34oD8tMxUvuo3bC-:b-103yy1) ([raw file](https://github.com/moka-guys/genomics_server_download/blob/93a749761a9e8dddb500838cb80c2d159ffe200b/script.py#L235)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

All of the tool names given to the logger function start with Archer so that they can be easily identified in the syslog. would you like all of these changed/removed?
</blockquote></details>

probably overkill!


<!-- Sent from Reviewable.io -->

2021-06-28 14:49 UTC, natashapinto approved these changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/genomics_server_download/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rebeccahaines1)



<!-- Sent from Reviewable.io -->

2021-06-28 14:50 UTC, merged